### ISSUE TITLE
Nuke 13 and Python 3 support

### ISSUE THREAD

**Issue by JenusL** [BinaryAlchemy/RoyalRender2020_render_apps#3]
Some things have already been changed to support python3 in the Nuke submitter but there's more things that has to be done as well.
https://github.com/BinaryAlchemy/RoyalRender2020_render_apps/blob/6fef741b195e91d05275cbb8959e79ae12636c48/_submitplugins/rrSubmit_Nuke_5.py#L201
has_key doesn't exist in py3 so it has to be changed to `if 'TEMP' in os.environ:`

And then we have some unicode issues with XML files.
This opens the file in text mode...
https://github.com/BinaryAlchemy/RoyalRender2020_render_apps/blob/6fef741b195e91d05275cbb8959e79ae12636c48/_submitplugins/rrSubmit_Nuke_5.py#L247

... but this tries to write in binary mode (default in python 3)
https://github.com/BinaryAlchemy/RoyalRender2020_render_apps/blob/6fef741b195e91d05275cbb8959e79ae12636c48/_submitplugins/rrSubmit_Nuke_5.py#L166

Solution is to write explicitly in unicode mode but this doesn't work in py2, so needs to be branched:
```
if sys.version_info.major > 2:
    xml.write(f, encoding='unicode')
else:
    xml.write(f)
```
After these changes it should work ok in both py2 and py3.

BONUS
Not really needed to run but I would also propose that open should use utf8 explicitly instead of system encoding, since ElementTree is unicode:
`tmpFile = open(tmpFileName, "w", encoding='utf8')`
This doesn't work in py2 but I usually fix this by overriding open in the beginning of the file:
```
if sys.version_info.major == 2:
    from io import open
```

**Comment by pKrime** [comment]
Hi Jenus,

please, have a look at my pull request #5 

We would not check os.environ at all if we leave the tempfile creation to python and get rid of _getNewTempFileName_ entirely.

Still, we could not pass the encoding parameter to python 2, but if it works on Nuke 13 anyway, I would leave it like this for now.

I plan to do some more checks on this plugin, so if you have more proposals, please let me know

**Comment by JenusL** [comment]
Ok I'll check and leave any comments in #5

**Comment by pKrime** [comment]
Ok, this is merged, thanks for the feedback! :)

**Comment by JenusL** [comment]
Ok cool! I'll test it right away.

**Comment by JenusL** [comment]
It seems to be working great in both Nuke 12 and 13. Thanks!
