### ISSUE TITLE
Request: Make Nuke submitter open in own terminal

### ISSUE THREAD

**Issue by JenusL** [BinaryAlchemy/RoyalRender2020_render_apps#4]
We find it a little bit annoying that every time you submit something from Nuke, rrSubmitter will fill the Nuke terminal with messages and change the colors.
This makes it much harder do detect actual errors from Nuke itself.
I don't know if this is an issue on Linux but it is for us on Windows at least.

So on Windows I would propose a change from this:
https://github.com/BinaryAlchemy/RoyalRender2020_render_apps/blob/6fef741b195e91d05275cbb8959e79ae12636c48/_submitplugins/rrSubmit_Nuke_5.py#L257-L261
To this:
``` python
    commandline=""
    if getOSString() == 'win':
        commandline = 'START "rrSubmitter" CMD /C '
    if nogui:
        commandline += getRRSubmitterconsolePath() + "  \"" + tmpFileName + "\"" + ' -Wait'
    else:
        commandline += getRRSubmitterPath()+"  \""+tmpFileName+"\""        
```

This will open the submitter in it's own command window.
If you want to make this behavior optional I'm fine with that.

**Comment by pKrime** [comment]
Hi Jenus,

please check my PR #6, commit c87bcd092a16c4c6f81535c63a92800329173038

if I use this command

`commandline = 'START "rrSubmitter" CMD /C '`

rrSubmitter's terminal is not closed after rrSubmitter is closed (probably due to the rrSubmitter command being a batch script).
I have to use 'START CMD /C  "rrSubmitter"'` instead. This shuts the terminal immediately, but we can disable the option when we have to debug

**Comment by JenusL** [comment]
That's very strange. Your code doesn't work for me because I think START really needs a "title" string before the command. I'll try some things and get back to you...

**Comment by JenusL** [comment]
From https://ss64.com/nt/start.html about the START command:
> Always include a TITLE this can be a simple string like "My Script" or just a pair of empty quotes ""
> According to the Microsoft documentation, the title is optional, but depending on the other options chosen you can have problems if it is omitted.

**Comment by JenusL** [comment]
@pKrime Thank you very much for listening and adding this :)
